### ISSUE TITLE
Cannot find module rimraf

### ISSUE THREAD

**Issue by crackernutter** [gbochenek/esri-wab-build#3]
Hi - very excited to see the capability demoed at the DevSummit a couple weeks ago - having problems implementing.  

I have node v7.7.4, bower v1.80, and Java - 
I've run npm install -g esri-wab-build
When I navigate to C:\arcgiswebappbuilderv24\server\apps\2 and run esri-wab-build command. 
I get the following error:

########## BUILD START TIME: Mon Mar 27 2017 14:55:11 GMT-0400 (Eastern Daylight Time) ##########
module.js:472
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\_svcArcGIS\AppData\Roaming\npm\node_modules\esri-wab-build\app\build:8:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Thoughts??

**Comment by gbochenek** [comment]
Try upgrading to 0.0.4 and giving that a go.  I added a more explicit dependency listing for rimraf.
