### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'your\webappp\path\buildOutput\app-packages'

### ISSUE THREAD

**Issue by g3r4n** [gbochenek/esri-wab-build#5]
Got the following issue when using the tools :
```
discovering resources...
starting reading resources...
starting processing raw resource content...
starting tokenizing resource...
starting processing resource tokens...
starting parsing resource...
{ Error: spawn java ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs:
   [ '-cp',
     'C:\\Workspace\\netviewwebapp\\build-src\\util\\closureCompiler\\compiler.jar;C:\\Workspace\\netviewwebapp\\build-src\\ut
il\\shrinksafe\\js.jar;C:\\Workspace\\netviewwebapp\\build-src\\util\\shrinksafe\\shrinksafe.jar',
     'org.mozilla.javascript.tools.shell.Main',
     'C:\\Workspace\\netviewwebapp\\build-src\\util\\build\\optimizeRunner.js' ] }
Error: spawn java ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
build always "fails"
fs.js:913
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Workspace\netviewwebapp\buildOutput\app-packages'
    at Object.fs.readdirSync (fs.js:913:18)
    at visitFolderFiles (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:435:18)
    at Object.cleanUncompressedSource (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:611:3
)
    at Object.exports.copy (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\copyapp.js:20:17)
    at Object.<anonymous> (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\build:82:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by g3r4n** [comment]
It failed because Java was not in the path 😠
