### ISSUE TITLE
Path error for jimu

### ISSUE THREAD

**Issue by g3r4n** [gbochenek/esri-wab-build#9]
got the following error  : 
```fs.js:960
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat 'C:\Workspace\netviewwebapp\buildOutput\app-packages\jimu'
    at Object.fs.lstatSync (fs.js:960:11)
    at Object.copySync (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\node_modules\fs-extra\lib\copy.js:62:18)
    at docopy (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:416:9)
    at Object.copyAppBuildPackages (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:377:3)
    at Object.exports.copy (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\copyapp.js:29:15)
    at Object.<anonymous> (C:\Users\ed032\AppData\Roaming\npm\node_modules\esri-wab-build\app\build:83:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)```

**Comment by g3r4n** [comment]
Issue due to build failed because of Java version
